config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles
  get "/users/profile",to: "users#profile"
  post "/users/profile_uodate",to: "users#profile_uodate"
  get "/rooms/myroom",to: "rooms#myroom"
  get "/rooms/reserve",to: "rooms#reserve"
  
  get 'home/index'
  devise_for :users
  root to: "rooms#index"
  resources :users 
  resources :rooms do
      collection do
        get 'search'
      end
    end
  resources :searches

  

  get 'reserve/index' # 入力画面
  get 'reserve/new' # 入力画面
  post 'reserve/confirm' # 確認画面
  post 'reserve/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reserve/complete' # 完了画面

   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord

    
end

app/models/reserve.rb
class Reserve < ApplicationRecord
      belongs_to :room #部屋データ
      belongs_to :user #ユーザーデータ



      

      def total_date
            (end_date - start_date).to_int/64800
      end

      
     
      def calc_total_price(price = 0)
            price * num_people * total_date.to_i
      end

      
end

app/models/room.rb
class Room < ApplicationRecord
    has_one_attached :image
    has_many :reserves #予約データ
    belongs_to :user #ユーザーデータ

    validates :room_name, presence: true
    validates :image, presence: true
    validates :room_price, presence: true,numericality: true
    validates :room_PR, presence: true ,length: { in: 1..50 }
    validates :room_address, presence: true

end

app/models/search.rb
class Search < ApplicationRecord
    def search_rooms

        rooms = Room.all
        rooms = Room.all
        rooms = rooms.where(["room_name LIKE ? ","%#{keywords}%"]) if keywords.present?
        rooms = rooms.where(["room_address LIKE ?","%#{area_search}%"]) if area_search.present?
        

        return rooms
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reserves #予約データ
  has_many :rooms #部屋データ

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :image

         validates :name, presence: true
         validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_q


    def apprication
        @search = Search.new
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def update
        @search = Search.create(search_params)
        redirect_to @search
    end

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
    
    def set_q
        @q = Room.ransack(params[:q])
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /profiles or /profiles.json
  def create
   
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice]="プロフィールを編集しました"
     redirect_to user_path(@user)
    else
     flash[:notice]="プロフィールを編集できませんでした"
     render"edit"
    end

  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    
  end

  private
    def user_params
      params.require(:user).permit(:profile, :image,:name)
    end
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController

	before_action :permit_params, except: :new

	def new
		@reserve = Reserve.new
		@room = Room.find(params[:id])
		@reservation.total_date = @reservation.end_date - @reservation.start_date
		
	end

	def back
		@reserve = Reserve.new(@attr)
		redirect_to :rooms
	end

	def confirm
		@room = Room.find(params[:room_id])
		@reserve = Reserve.new(@attr)
		@search = Search.new
		@user = current_user
		@reserve.user_id = current_user.id	
		session[:reserve] = @reserve
		if @reserve.invalid?
			#redirect_to :rooms/(room)
		else
		end
	end

	def complete
		@room = Room.find(params[:room_id])
		@reserve = Reserve.new(@attr)
		@reserve.save
		@search = Search.new
		
	end

	private

	def permit_params

		@attr = (params.require('reserve').permit(:id, :user_id, :room_id, :start_date, :end_date, :num_people, :total_price, :total_date,:reserve_date,:name,:note))
	end

	
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q
  def reserve
    @reserve = current_user.reserves
  end
  
  def myroom
    @rooms = Room.all
  end
 
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @reserve = Reserve.new
    @search = Search.new
  end

  def new
    @room = Room.new
    @search = Search.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if@room.save
      flash[:notice]="新しい部屋を登録しました"
      redirect_to room_path(@room)
    else
      flash[:notice]="部屋を登録できませんでした"
      render"new"
    end 
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
   if @room.update(room_params)
    flash[:notice]="部屋を編集しました"
    redirect_to room_path(@room)
   else
    flash[:notice]="部屋を編集できませんでした"
    render"edit"
   end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  def search
    @results = @q.result
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :room_PR, :room_price, :room_address,:image,:total_price,)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new
        @search = Search.new
        #@categories = Book.uniq.pluck(:category)
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def show
        
        @search = Search.find(params[:id])
        @users = User.all
        @rooms = Room.all
       
        
    end

    private

    def search_params
       params.require(:search).permit(:keywords, :category, :min_price, :max_price, :isbn)
    end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

    # GET /resource/sign_up
    def new
      super
    end
    
    # POST /resource
    def create
      #super
      #独自ロジックを記述
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:id])
  end

  def profile_update
    @user = User.find(params[:id])
    @user.plofile_update(user_params)
    redirect_to user_plofile_path(@user)
  end

  
  def index
    @users = User.all
    @rooms = Room.all
    @search = Search.new
  end

  def show
    @user = User.find(params[:id])
    @search = Search.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def registrantions
    @search = Search.new
  end

  def sessions
    @search = Search.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :encrypted_password,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

 <%= f.submit "検索結果" %>
 <%= link_to "検索結果のページへリング", "/searchs/id" %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<!--サイドバー部分-->
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                
                     <%= link_to("アカウント", "/users/#{current_user.id}", {class: "sidebar-account"}) %>
                     <%= link_to("プロフィール", "/profiles/#{current_user.id}/edit", {class: "sidebar-profile"}) %>
                
                <hr>
            </div>
        </div>
     
 
<!--メイン部分-->
        <div class="profile-content-edit">
          
            <div class="profile-edit">
                <h1>プロフィールページ</h1>
                  <%= form_for @user do |f| %>

                    <div class="field">
                    　 <% if current_user.image.attached?%>
                           <%= image_tag @user.image,class:'profile-user-image' %>
                       <% else %>
                           <% image_tag 'no-image.user.png',class:'profile-user-image' %>
                       <% end %>   
                      <br>
                      <%= f.file_field :image %>
                    </div>

                  　<div class="field">　
                      <%= f.label :名前 ,class:'field-text'%><br />
                      <%= f.text_field :name, autofocus: true, autocomplete: "名前",class:'field-box' %>
                    </div>

                    <div class="field">
                      <%= f.label :自己紹介 ,class:'field-text'%><br />
                      <%= f.text_area :profile, autofocus: true, autocomplete: "自己紹介を入力" ,class:'field-box'%>
                    </div>


                    <div class="actions">
                      <%= f.submit "更新" %>
                    </div>

                  <% end %>


            </div>
        
    </div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<!--このページは使ってない-->

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_profile_path(@profile) %> 
<%= link_to 'Back', profiles_path %>

app/views/reserve/complete.html.erb
<h1>ご予約ありがとうございました。</h1>

<h1>予約内容確定</h1>
<div>
   <dt>¥<%= @room.room_price %>/日<dt>
	<dl>
		
		<dt>開始日</dt>
		<dd><%= @reserve.start_date.strftime('%Y年%m月%d日') %></dd>
		<dt>終了日</dt>
		<dd><%= @reserve.end_date.strftime('%Y年%m月%d日')  %></dd>
		
		<dt>使用日数：</dt>
		<dd><%= @reserve.total_date %></dd>
		<dt>人数：</dt>
		<dd><%= @reserve.num_people %></dd>
		<dt>合計金額</dt>
		<dd><%= @reserve.calc_total_price(@room.room_price) %></dd>
	</dl>
</div>

app/views/reserve/confirm.html.erb
<h1>予約内容確認</h1>
<div>
   
		<dt>部屋名：</dt>
		<dd><%= @room.room_name %></dd>
		<dt>部屋金額：</dt>
		<dd><%= @room.room_price %></dd>
		<dt>開始日</dt>
		<dd><%= @reserve.start_date.strftime('%Y年%m月%d日')  %></dd>
		<dt>終了日</dt>
		<dd><%= @reserve.end_date.strftime('%Y年%m月%d日')  %></dd>
		
		<dt>使用日数：</dt>
		<dd><%= @reserve.total_date %></dd>
		<dt>人数：</dt>
		<dd><%= @reserve.num_people %></dd>
		<dt>合計金額</dt>
		<dd><%= @reserve.calc_total_price(@room.room_price) %></dd>
	</dl>
	<p>上記内容でよろしければ「予約を確定」を押してください</p>

	<%= form_for @reserve, method: :post, url: reserve_complete_path(room_id:@room.id) do |form| %>
		<%= form.hidden_field :name %>
		<%= form.hidden_field :note %>
		<%= form.hidden_field :room_id, value: @room.id %>
		<%= form.hidden_field :start_date %>
		<%= form.hidden_field :end_date %>
		<%= form.hidden_field :total_date %>
		<%= form.hidden_field :num_people %>
		<%= form.hidden_field :user_id, value: current_user.id %>
		<%= form.hidden_field :total_price,value: @reserve.calc_total_price(@room.room_price) %>

		<%= form.submit '予約を確定する' %>
	<% end %>

	<%= form_for @reserve, method: :post, url: reserve_back_path do |form| %>
		<%= form.submit 'ルーム詳細に戻る' %>
	<% end %>

	
</div>

app/views/reserve/index.html.erb
<!--使ってない-->

app/views/reserve/new.html.erb
<h1>予約フォーム</h1>

<div class="room_show">
<h3>こちら側にルームの詳細ページが入ります</h3>
</div>

<div class="reservation_new">
	
	<%= form_for @room, method: :get, url: reserve_confirm_path do |form| %>
		<dl>
			<dt>¥６０００/日<dt>
			<dd><%= @room. room_price %></dd>
		</dl>
	<% end %>
	<%= form_for @reserve, method: :post, url: reserve_confirm_path do |form| %>
		<dl>
			<dt>¥６０００/日<dt>
			<dt>開始日</dt>
			<dd><%= form.date_field :start_date %></dd>
			<dt>終了日</dt>
			<dd><%= form.date_field :end_date %></dd>
			<dt>人数</dt>
			<dd><%= form.number_field :num_people %></dd>
		</dl>

		<%= form.submit '確認画面へ' %>
	<% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>
<h2>room編集ページ</h2>

app/views/rooms/index.html.erb
<div class="top_area">
  <div class="background-photo">
    
    
    <div class="search-box"><!--検索フォーム-->
        <div class="search-text">
          <h1>Potepan Shareでまだ体験したことのない旅をしよう</h1>
        </div>

          <%= search_form_for @q, url: search_rooms_path do |f| %>
              
              <%= f.search_field :room_name_or_room_address_or_room_PR_cont ,placeholder: "キーワード検索" %>
              <br>
              <%= f.submit '検索' %>
          <% end %>

      </div>
  </div>
</div>

<div class="second_area">

<h2>おすすめエリア</h2>

  <div class="city_area">

    <div class="city">
        <a href="/rooms/search?q%5Broom_address_cont%5D=東京" ><img src='https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg'></a>
        <p><%= link_to "", "/rooms/search?q%5Broom_address_cont%5D=東京" %></p>
        <h3>東京</h3>
    </div>

    <div class="city">
        <a href="/rooms/search?q%5Broom_address_cont%5D=大阪" ><img src='https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg'></a>
        <p><%= link_to "", "/rooms/search?q%5Broom_address_cont%5D=大阪" %></p>
        <h3>大阪</h3>
    </div>

    <div class="city">
        <a href="/rooms/search?q%5Broom_address_cont%5D=京都府" ><img src='https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg'></a>
        <p><%= link_to "", "/rooms/search?q%5Broom_address_cont%5D=京都府" %></p>
        <h3>京都</h3>
    </div>

    <div class="city">
        <a href="/rooms/search?q%5Broom_address_cont%5D=札幌" ><img src='https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg'></a>
        <p><%= link_to "", "/rooms/search?q%5Broom_address_cont%5D=札幌" %></p>
        <h3>札幌</h3>
    </div>


  </div>
</div>
  

app/views/rooms/myroom.html.erb
<h1>my登録部屋一覧</h1>

app/views/rooms/new.html.erb
<h1>ルーム情報登録</h1>

 <%= render "shared/error", obj: @room %>

<%= form_for @room do |f| %>
    <div class="new_box">
        <div class="new_box_wrap">
            <div class="field">　
                <tr>
                    <th><%= f.label :ルームイメージ %></th><br />
                    <td><%= f.file_field :image %></td>
                </tr>
            </div>
            <div class="field">　
                <tr>
                    <th><%= f.label :ルーム名 %></th><br />
                    <td><%= f.text_field :room_name %></td>
            </div>
            <div class="field">　
                <tr>
                    <th><%= f.label :ルーム紹介 %></th><br />
                    <td><%= f.text_area :room_PR%></td>
            </div>
            <div class="field">　
                <tr>
                    <th><%= f.label :料金 %></th><br />
                    <td><%= f.text_field :room_price %></td>
            </div>
            <div class="field">　
                <tr>
                    <th><%= f.label :住所 %></th><br />
                    <td><%= f.text_field :room_address %></td>
            </div>
                <%= f.submit  "登録" %>
        </div>
    </div>
<% end %>

app/views/rooms/reserve.html.erb
<div class="content">
  <h1>予約済みルーム一覧</h1>

  <div class="rooms-index-list">
    <table>
          <thead>
            <tr>
        　　　<th>ルーム画像</th>
        　　　<th>ルーム名</th>
        　　　<th>ルーム紹介</th>
        　　　<th>合計金額</th>
        　　　<th>開始日</th>
             <th>終了日</th>
             <th>予約確定日</th>
          </tr>
        </thead>
          <tbody>
            <% @reserve.each do |reserve| %>
              　<tr>

                <td><%= image_tag reserve.room.image %></td>
                <td><%= link_to room_path(reserve.room) do%>
                  　　<%= reserve.room.room_name %>
                    <% end %></td>

                <td> <%= reserve.room.room_PR %></td>
                <td> <%=  reserve.total_price %></td><!--不明-->
                <td> <%= reserve.start_date.strftime('%Y年%m月%d日')  %></td>
                <td> <%= reserve.end_date.strftime('%Y年%m月%d日')  %></td>
                <td> <%= reserve.created_at.strftime('%Y年%m月%d日')  %></td>


               
                
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/rooms/search.html.erb
<h1>検索結果</h1>

<div class="content">
  <div class="card-wrap">
   
        <table>
            <tbody>
              <% @results.each do |room| %>
               <%= link_to room_path(room) do %>
                <div class="card-list">
                  <p><%= image_tag room.image ,class:'search-image'%></p>
                    <h1 class="card-listImage"><%= room.room_name %></h1>
                    <h2 class="card-listImage"><%= room.room_price %>円</h2>
                    <h4 class="card-listPR"><%= room.room_PR %></h4>
                </div>
                <% end %>
              <% end %>
            </tbody>
        </table>

        <%= link_to 'Top', rooms_path %>
    
  </div>
</div>

app/views/rooms/show.html.erb
<div>
  <div class="room-show">
    <div class="content-wrap">
      <div class="room-show-wrap">
              <div class="room-show-image">
                  <%= image_tag @room.image ,class:'show-image'%>
              </div>
              <div class="room-show-text">
                      <p class="showText"><%= @room.room_name %></p>  
                      <p class="showText"><%= @room.room_address %></p>
                      <p class="showText"><%= @room.room_PR %></p>
              </div>
      </div>

      <div class="reservation-new-wrap">
        
              <div>
                  <dt>¥<%= @room.room_price %>/日<dt>
              </div>
        
        
          <%= form_for @reserve, method: :post, url: reserve_confirm_path(room_id:@room.id) do |form| %>
              <dl>
                  
                  <dt>開始日</dt>
                  <dd><%= form.date_field :start_date %></dd>
                  <dt>終了日</dt>
                  <dd><%= form.date_field :end_date %></dd>
                  <dt>人数</dt>
                  <dd><%= form.number_field :num_people %></dd>
              </dl>
              <%= form.hidden_field :room_id,value: @room.id %>
              
              <%= form.submit '確認画面へ' %>
          <% end %>
        
      </div>
    </div>
  </div>
</div>

 

app/views/searches/new.html.erb
 <!--使ってない-->   
<div class="background-photo">
  <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/img_cover_top.jpg' %>
   
   <div class="search-box">
      <div class="search-text">
        <h1>Potepan Shareでまだ体験したことのない旅をしよう</h1>
      </div>
      <%= form_for @search, html: {class:"pure-form"} do |s| %>

        <div class="field">
          <%= s.label :エリア %>
          <%= s.text_field :keywords %>
        </div>

        <div class="actions"><%= s.submit "探す"%></div>
      <% end %>
    </div>
</div>
<div class="search-ereas">
      <div class="tokyo">
        <%= link_to root_path do %>
        <div class="eraebox">
          <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg' %>
        </div>
        <p>東京</p>
        <% end %>
      </div>

      <div class="osaka">
        <%= link_to root_path do %>
        <div class="eraebox">
          <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg' %>
        </div>
        <p>東京</p>
        <% end %>
      </div>

      <div class="fukuoka">
        <%= link_to root_path do %>
        <div class="eraebox">
          <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/img_fukuoka.jpg' %>
        </div>
        <p>東京</p>
        <% end %>
      </div>

      <div class="sapporo">
        <%= link_to root_path do %>
        <div class="eraebox">
          <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg' %>
        </div>
        <p>東京</p>
        <% end %>
      </div>
<div>

    <p><%= link_to "戻る",rooms_path %></p>
  </div>

app/views/searches/show.html.erb
<!--使ってない-->
<h1>検索ページgitgi</h1>

<p><%= link_to "戻る",new_search_path %></p>

<% if @search.search_rooms.empty?%>

  <p>何もないよ</p>

<% else %>

  <% @search.search_rooms.each do |c| %>
    <br>

    <div class="search_box">
     
    
      <h1><%= c.room_name %></h1>
      <p>料金<%= c.room_price %></p>
      <p>住所:<%= c.room_address %></p>
      <p>ルーム情報:<%= c.room_PR %></p>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="content-edit">
  <h1>アカウント編集</h1>

  <div class="user-edit">

<%= form_for @user do |f| %>

<div class="field">
    
  <div class="field">
    <%= f.label :メールアドレス  ,class:'field-text'%><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" ,class:'field-box'%>
  </div>

  <div class="field">
    <%= f.label :変更後パスワード  ,class:'field-text'%>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" ,class:'field-box'%>
  </div>

  <div class="field">
    <%= f.label :パスワード確認用用（変更する場合のみ入力） ,class:'field-text'%><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password",class:'field-box'%>
  </div>

  <div class="field">
    <%= f.label :現在のパスワード） ,class:'field-text'%><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" ,class:'field-box'%>
  </div>


   <div class="actions">
    <%= f.submit "更新" %>
  </div>

<% end %>

<%= link_to "戻る", "/users/#{current_user.id}" ,class: "button is-warning is-light"%>

app/views/users/index.html.erb
<div class="content">
  <h1>登録済みルーム一覧</h1>

  <div class="rooms-index-list">
    <table>
          <thead>
            <tr>
        　　　<th>ルーム画像</th>
        　　　<th>ルーム名</th>
        　　　<th>ルーム紹介</th>
        　　　<th>料金</th>
        　　　<th>作成日</th>
          </tr>
        </thead>
    
          <tbody>
            <% @rooms.each do |room| %>
              　<tr>
                <td><%= image_tag room.image ,class:'user-index-image'%></td>

                <td><%= link_to room_path(room),class:'room-name-link' do%>
                  　　<%= room.room_name %>
                  <% end %></td>

                
                <td><%= room.room_PR %></td>
                <td>¥<%= room.room_price %></td>
                <td><%= room.updated_at.strftime('%Y年%m月%d日') %></td>

                </td>
                
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/users/profile.html.erb
<!--このページは使われてないです-->


<div class="content-profile">
  <h1>プロフィールページ</h1>

  <div class="user-profile">
        <%= form_for @user do |f| %>

        <div class="field">
            
          <div class="field">
            <%= f.label :メールアドレス %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :変更後パスワード %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password" %>
          </div>

          <div class="field">
            <%= f.label :パスワード確認用用（変更する場合のみ入力） %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>

          <div class="field">
            <%= f.label :現在のパスワード） %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>


          <div class="actions">
            <%= f.submit "更新" %>
          </div>

        <% end %>

        <%= link_to "戻る", "/users/#{current_user.id}" ,class: "button is-warning is-light"%>
    </div>
</div>

app/views/users/show.html.erb
<!--サイドバー部分-->
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                
                     <%= link_to("アカウント", "/users/#{current_user.id}", {class: "sidebar-account"}) %>
                     <%= link_to("プロフィール", "/profiles/#{current_user.id}/edit", {class: "sidebar-profile"}) %>
                
                <hr>
            </div>
        </div>

<!--メイン部分-->

<div class="user-show-main">
    <div class="user-show-wrap">
          <h1>アカウント設定</h1>
          
              <div class="field">　
                  <th>メールアドレス</th>
                  <td><%= @user.email %></td>
                </tr>
              </div>
              <div class="field">　
                <tr>
                  <th>パスワード</th>
                  <td>********</td>
                </tr>
              </div>
              
              </table>
          
              <div>
                  <%= link_to "編集", [:edit, @user], class: "button is-warning is-light" %>   
            </div>
    </div>
</div>