config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles
  get "/users/profile",to: "users#profile"
  post "/users/profile_uodate",to: "users#profile_uodate"
  get "/rooms/myroom",to: "rooms#myroom"
  get "/rooms/reserve",to: "rooms#reserve"
  
  get 'home/index'
  devise_for :users
  root to: "rooms#index"
  resources :users 
  resources :rooms do
      collection do
        get 'search'
      end
    end
  resources :searches

  

  get 'reserve/index' # 入力画面
  get 'reserve/new' # 入力画面
  post 'reserve/confirm' # 確認画面
  post 'reserve/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reserve/complete' # 完了画面

   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord

    
end

app/models/reserve.rb
class Reserve < ApplicationRecord
      belongs_to :room #部屋データ
      belongs_to :user #ユーザーデータ



      

      def total_date
            (end_date - start_date).to_int/64800
      end

      
     
      def calc_total_price(price = 0)
            price * num_people * total_date.to_i
      end

      
end

app/models/room.rb
class Room < ApplicationRecord
    has_one_attached :image
    has_many :reserves #予約データ
    belongs_to :user #ユーザーデータ

    validates :room_name, presence: true
    validates :image, presence: true
    validates :room_price, presence: true,numericality: true
    validates :room_PR, presence: true ,length: { in: 1..50 }
    validates :room_address, presence: true

end

app/models/search.rb
class Search < ApplicationRecord
    def search_rooms

        rooms = Room.all
        rooms = Room.all
        rooms = rooms.where(["room_name LIKE ? ","%#{keywords}%"]) if keywords.present?
        rooms = rooms.where(["room_address LIKE ?","%#{area_search}%"]) if area_search.present?
        

        return rooms
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reserves #予約データ
  has_many :rooms #部屋データ

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :image

         validates :name, presence: true
         validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_q


    def apprication
        @search = Search.new
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def update
        @search = Search.create(search_params)
        redirect_to @search
    end

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
    
    def set_q
        @q = Room.ransack(params[:q])
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /profiles or /profiles.json
  def create
   
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice]="プロフィールを編集しました"
     redirect_to user_path(@user)
    else
     flash[:notice]="プロフィールを編集できませんでした"
     render"edit"
    end

  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    
  end

  private
    def user_params
      params.require(:user).permit(:profile, :image,:name)
    end
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController

	before_action :permit_params, except: :new

	def new
		@reserve = Reserve.new
		@room = Room.find(params[:id])
		@reservation.total_date = @reservation.end_date - @reservation.start_date
		
	end

	def back
		@reserve = Reserve.new(@attr)
		redirect_to :rooms
	end

	def confirm
		@room = Room.find(params[:room_id])
		@reserve = Reserve.new(@attr)
		@search = Search.new
		@user = current_user
		@reserve.user_id = current_user.id	
		session[:reserve] = @reserve
		if @reserve.invalid?
			#redirect_to :rooms/(room)
		else
		end
	end

	def complete
		@room = Room.find(params[:room_id])
		@reserve = Reserve.new(@attr)
		@reserve.save
		@search = Search.new
		
	end

	private

	def permit_params

		@attr = (params.require('reserve').permit(:id, :user_id, :room_id, :start_date, :end_date, :num_people, :total_price, :total_date,:reserve_date,:name,:note))
	end

	
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q
  def reserve
    @reserve = current_user.reserves
  end
  
  def myroom
    @rooms = Room.all
  end
 
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @reserve = Reserve.new
    @search = Search.new
  end

  def new
    @room = Room.new
    @search = Search.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if@room.save
      flash[:notice]="新しい部屋を登録しました"
      redirect_to room_path(@room)
    else
      flash[:notice]="部屋を登録できませんでした"
      render"new"
    end 
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
   if @room.update(room_params)
    flash[:notice]="部屋を編集しました"
    redirect_to room_path(@room)
   else
    flash[:notice]="部屋を編集できませんでした"
    render"edit"
   end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to rooms_path
  end

  def search
    @results = @q.result
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :room_PR, :room_price, :room_address,:image,:total_price,)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new
        @search = Search.new
        #@categories = Book.uniq.pluck(:category)
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end

    def show
        
        @search = Search.find(params[:id])
        @users = User.all
        @rooms = Room.all
       
        
    end

    private

    def search_params
       params.require(:search).permit(:keywords, :category, :min_price, :max_price, :isbn)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:id])
  end

  def profile_update
    @user = User.find(params[:id])
    @user.plofile_update(user_params)
    redirect_to user_plofile_path(@user)
  end

  
  def index
    @users = User.all
    @rooms = Room.all
    @search = Search.new
  end

  def show
    @user = User.find(params[:id])
    @search = Search.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def registrantions
    @search = Search.new
  end

  def sessions
    @search = Search.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :encrypted_password,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>宿泊サイト</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>

  <body>
     <div class="flash-box">
              <% if flash[:notice] %>
                <div class="notification is-info">
                  <p class="notice"><%= notice %></p>
                </div>
              <% end %>

              <% if flash[:alert] %>
                <div class="notification is-danger">
                  <p class="alert"><%= alert %></p>
                </div>
              <% end %>
     </div>
     
      <header>
        <%= render "shared/partial" %><!--sharedに実装-->
      </header>
      <main>
         <%= yield %>
      </main>
   <!--<footer>-->
      <footer>
        <%= render "shared/partial2" %><!--sharedに実装-->
      </footer>
   <!-- </footer>-->
    
  </body>
      

</html>

app/views/shared/_error.html.erb
    <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>

app/views/shared/_partial.html.erb
<!---ヘッダーを実装-->
           
          <div class="header-top-ul">
            <% if user_signed_in? %>
              <ul >
                   <li><%= link_to "ルームを登録する", "/rooms/new" ,class: "header-link"%></li>
                   <li> <%= link_to "登録済みルーム", users_path(current_user) ,class: "header-link" %></li>
                   <li> <%= link_to "予約済みルーム", "/rooms/reserve" ,class: "header-link"%></li>
                   <li><%= link_to "設定ページ", user_path(current_user) ,class: "header-link"%></li>
                   <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "header-link"%></li>
             </ul>
            <% end %>
          </div>

<div class="header_area">     
    <div class="lefterea">
                
      <div class="searchbox_area">
        
                <div class="logo">
                  <%= link_to root_path, class: "rogo" do %>
                    <%= image_tag 'https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png'  %>
                  <% end %>
                 
                </div>

                <div class="searchbox">
                  <%= search_form_for @q, url: search_rooms_path do |f| %>  
                      <%= f.search_field :room_name_or_room_address_or_room_PR_cont ,placeholder: "キーワード検索",class: "searchFieldBox"%>
                      <div class="icon"><!--キーワード検索アイコン-->
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" color="black"class="bi bi-search" viewBox="0 0 16 16">
                      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/></svg>
                      </div>
                  <% end %>
                </div>

                <div class="searchbox">
                  <%= search_form_for @q, url: search_rooms_path do |f| %>  
                      <%= f.search_field :room_address_cont ,placeholder: "エリア検索",class: "searchFieldBox"%>
                      <div class="icon"><!--エリア検索アイコン-->
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" color="black" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/></svg>     
                      </div>
                  <% end %>
                </div>
       </div>  
          
   </div>
   <div class="center_area">
   <a></a>
   
   </div>
    <div class="right_area">  
                <% if user_signed_in? %>
                 <div class="user_info">
                          <div class="user_name">
                              <%= current_user.name %>
                          </div>
                          <div class="user_icon"> 
                               <% if current_user.image.attached? %>
                                        <%= image_tag current_user.image,class: 'header-user-image' %>
                                      <% else %>
                                        <%= image_tag 'no-image.user.png' ,class: 'header-user-image'%>
                                      <% end %>

                          </div>
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                     
                           </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                  <li><%= link_to "ルームを登録する", "/rooms/new" ,class: "header-link"%></li>
                                  <li> <%= link_to "登録済みルーム", users_path(current_user)  ,class: "header-link"%></li>
                                  <li> <%= link_to "予約済みルーム", "/rooms/reserve" ,class: "header-link"%></li>
                                  <li><%= link_to "設定ページ", user_path(current_user) ,class: "header-link"%></li>
                                  <li> <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "header-link"%></li>
                            </ul>
                           </div>
               
                <% else %>
                    <div class="logbutton">
                        <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>   
                        <%= link_to "新規登録", new_user_registration_path,  class: "button is-warning is-light" %>
                    </div>
                <% end %>

                
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
   </div>           
</div>       

app/views/shared/_partial2.html.erb
<div id="footerWrap">
	<div id="footer">
	    <p>© 2021 POTEPAN.INC.</p>
	</div>
</div>